<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIpzvQG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIpzvQG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRIpzvQG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRIpzvQG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRIpzvQG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RIpzvQG',
    'container.build_id' => '4dfb8e54',
    'container.build_time' => 1648050585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIpzvQG');
